version: 2.1
jobs:
    build:
        docker:
            - image: cimg/node:14.17.5
        steps:
            - checkout
            - run: echo "npm installing"
            - run: npm install
            - run: CI=true npm run build
    # test:
    #     docker:
    #         - image: cimg/node:14.17.5
    #     steps:
    #         - checkout
    #         - run: echo "testing code"
    #         - run: npm install
    #         - run: npm test
    deploy:
        docker:
            - image: cimg/node:14.17.5
        steps:
            - checkout
            - run: echo "deploying code"
            - run: npm install
            - run: npm run deploy
workflows:
    build_test_deploy:
        jobs:
            - build
            # - test
            - deploy
